navbar-links:
    Archive: /archives
    Github: https://github.com/kctechgroup
    Slack: https://kctechgroup.slack.com
    About: /about/

avatar: /hexo.png
favicon: /hexo.png

header:
    title: "Kansas City Technology Group"
    motto: Technology and Automation Enthusiasts Welcome!
    bigimgs:
        - src: /bigimgs/01.jpg
          desc: 
        - src: /bigimgs/02.jpg
          desc: 
        - src: /bigimgs/03.jpg
          desc: 

rss: /atom.xml
googlefonts:
  - "Lora:400,700,400italic,700italic"
  - "Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"

highlight:
  enable: true
# or use any highlight.js style
#  style_path: "//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/styles/default.min.css"
  style_path: "/css/highlight.css"

footer:
  facebook:
    link: # your link e.g. https://...
    title: Facebook
    icon: fa-facebook
    enalbe: false
  weibo:
    link: 'http://weibo.com/bisyao?is_all=1'
    title: Weibo
    icon: fa-weibo
    enalbe: false
  github:
    link: 'https://github.com/kctechgroup'
    title: GitHub
    icon: fa-github
    enable: true
  rss:
    link: '/atom.xml'
    title: RSS
    icon: fa-rss
    enable: true
  twitter:
    link: 'https://twitter.com/twoyao_'
    title: Twitter
    icon: fa-twitter
    enable: false
  mail:
    link: 'mailto:bisyao@gmail.com'
    title: Email me
    icon: fa-envelope
    enable: false
  linkin:
    link: # your link here e.g. http...
    title: LinkedIn
    icon: fa-linkedin
    enable: false
  stackoverflow:
    link: # your link here e.g. http...
    title: StackOverflow
    icon: fa-stack-overflow
    enable: false

google_analytics:

comment:
  enable: true
  disqus: kctechgroup

